export const FIELD_LABELS = {
  applicationReference: "Application reference",
  submittedAt: "Submitted at",
  fullName: "Full name",
  fullNameLatin: "Full name (Latin)",
  hasPreviousName: "Previous name",
  previousName: "Previous name (details)",
  dateOfBirth: "Date of birth",
  nationality: "Nationality",
  sex: "Sex",
  idPassportNumber: "ID / Passport number",
  issuedBy: "Issued by",
  expirationDate: "Expiration date",
  currentAddress: "Current address",
  permanentAddress: "Permanent address",
  phone: "Phone",
  email: "Email",
  hasSpouse: "Has spouse",
  spouseFullName: "Spouse — full name",
  spouseFullNameLatin: "Spouse — Latin name",
  spouseSex: "Spouse — sex",
  spouseAddress: "Spouse — address",
  spousePhone: "Spouse — phone",
  spouseEmail: "Spouse — email",
  hasMonthlyIncome: "Has monthly income",
  monthlyIncomeAfterTax: "Monthly income after tax ($)",
  otherIncomeSources: "Source of other income",
  otherIncomeSourceDetails: "Other income source (details)",
  employmentStatus: "Employment status",
  industry: "Industry",
  occupation: "Occupation / Job title",
  employerName: "Employer / Business name",
  workplaceAddress: "Workplace address",
  workplaceContact: "Workplace contact",
  workingPeriod: "Working period",
  yearsWorkingExperience: "Years of working experience",
  educationalLevel: "Educational level",
  derivativeKnowledge: "Derivative knowledge",
  investmentObjectives: "Investment objectives",
  experienceOtherFinancialMarkets: "Other financial markets experience",
  financialMarket1Name: "Market 1 — name",
  financialMarket1ProductType: "Market 1 — product type",
  financialMarket1Country: "Market 1 — country",
  financialMarket1Year: "Market 1 — year",
  financialMarket2Name: "Market 2 — name",
  financialMarket2ProductType: "Market 2 — product type",
  financialMarket2Country: "Market 2 — country",
  financialMarket2Year: "Market 2 — year",
  qualifiedInvestor: "Qualified investor",
  qualifiedInvestorCriteria: "Qualified investor criteria",
  hasAuthorizedPerson: "Authorized person",
  authorizedPersonName: "Authorized person — name",
  authorizedPersonRelationship: "Authorized person — relationship",
  beneficialOwner: "Beneficial owner",
  controllingPerson: "Controlling person",
  moneyLaunderingRecordLast3Years: "Money laundering record (last 3 years)",
  moneyLaunderingRecordDetails: "Money laundering record — details",
  contactPreferences: "Margin call contact methods",
  marginCallContactPhone: "Margin call — phone",
  marginCallContactEmail: "Margin call — email",
  marginCallContactFax: "Margin call — fax",
  marginCallContactOthers: "Margin call — other",
  relationshipDerivativeBroker: "Relationship with derivative broker",
  derivativeBrokerEmployeeName: "Derivative broker — employee name",
  derivativeBrokerRelationship: "Derivative broker — relationship",
  relationshipCentralCounterparty: "Relationship with central counterparty",
  counterpartyEmployeeName: "Counterparty — employee name",
  counterpartyCompanyName: "Counterparty — company name",
  counterpartyRelationship: "Counterparty — relationship",
  investmentObjectiveOtherDetails: "Investment objective — other",
  emergencyContactFullName: "Emergency contact — full name",
  emergencyContactFullNameLatin: "Emergency contact — Latin name",
  emergencyContactSex: "Emergency contact — sex",
  emergencyContactAddress: "Emergency contact — address",
  emergencyContactPhone: "Emergency contact — phone",
  emergencyContactEmail: "Emergency contact — email",
  attachedDocumentType: "Attached document type",
  otherDocumentDescription: "Other document description",
  idCardCopy: "ID card copy",
  passportVisaCopy: "Passport / Visa copy",
  familyRecordBookCopy: "Family record book copy",
  otherDocumentCopy: "Other document",
  thirdPartyVerificationStarted: "Third-party verification started",
  agreementAccepted: "Agreement accepted",
  clientSignature: "Client signature",
  signatureFile: "Signature file",
  locale: "Locale",
  createdAt: "Created at",
};

export const DETAIL_SECTIONS = [
  {
    title: "Application summary",
    keys: ["applicationReference", "submittedAt", "locale", "createdAt"],
  },
  {
    title: "Personal information",
    keys: [
      "fullName",
      "fullNameLatin",
      "hasPreviousName",
      "previousName",
      "dateOfBirth",
      "nationality",
      "sex",
      "idPassportNumber",
      "issuedBy",
      "expirationDate",
      "currentAddress",
      "permanentAddress",
      "phone",
      "email",
      "hasSpouse",
      "spouseFullName",
      "spouseFullNameLatin",
      "spouseSex",
      "spouseAddress",
      "spousePhone",
      "spouseEmail",
      "hasMonthlyIncome",
      "monthlyIncomeAfterTax",
      "otherIncomeSources",
      "otherIncomeSourceDetails",
    ],
  },
  {
    title: "Employment",
    keys: [
      "employmentStatus",
      "industry",
      "occupation",
      "employerName",
      "workplaceAddress",
      "workplaceContact",
      "workingPeriod",
      "yearsWorkingExperience",
    ],
  },
  {
    title: "Questionnaire",
    keys: [
      "educationalLevel",
      "derivativeKnowledge",
      "investmentObjectives",
      "experienceOtherFinancialMarkets",
      "financialMarket1Name",
      "financialMarket1ProductType",
      "financialMarket1Country",
      "financialMarket1Year",
      "financialMarket2Name",
      "financialMarket2ProductType",
      "financialMarket2Country",
      "financialMarket2Year",
      "qualifiedInvestor",
      "qualifiedInvestorCriteria",
      "hasAuthorizedPerson",
      "authorizedPersonName",
      "authorizedPersonRelationship",
      "beneficialOwner",
      "controllingPerson",
      "moneyLaunderingRecordLast3Years",
      "moneyLaunderingRecordDetails",
      "contactPreferences",
      "marginCallContactPhone",
      "marginCallContactEmail",
      "marginCallContactFax",
      "marginCallContactOthers",
      "relationshipDerivativeBroker",
      "derivativeBrokerEmployeeName",
      "derivativeBrokerRelationship",
      "relationshipCentralCounterparty",
      "counterpartyEmployeeName",
      "counterpartyCompanyName",
      "counterpartyRelationship",
      "investmentObjectiveOtherDetails",
      "emergencyContactFullName",
      "emergencyContactFullNameLatin",
      "emergencyContactSex",
      "emergencyContactAddress",
      "emergencyContactPhone",
      "emergencyContactEmail",
    ],
  },
  {
    title: "Documents & verification",
    keys: [
      "attachedDocumentType",
      "otherDocumentDescription",
      "idCardCopy",
      "passportVisaCopy",
      "familyRecordBookCopy",
      "otherDocumentCopy",
      "thirdPartyVerificationStarted",
    ],
  },
  {
    title: "Agreement & signature",
    keys: ["agreementAccepted", "clientSignature", "signatureFile"],
  },
];

export function formatFieldValue(value) {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (Array.isArray(value)) {
    if (value.length === 0) return "—";
    return value.join(", ");
  }
  if (typeof value === "object") {
    if (value.url) {
      return value;
    }
    if (value.fileName) {
      const kb = value.fileSize ? ` (${Math.round(value.fileSize / 1024)} KB)` : "";
      return `${value.fileName}${kb}`;
    }
    return JSON.stringify(value);
  }
  if (value === "yes") return "Yes";
  if (value === "no") return "No";
  return String(value);
}

export function isDocumentLinkValue(value) {
  return value && typeof value === "object" && typeof value.url === "string" && value.url.length > 0;
}

export function buildSubmissionDetailRecord(row) {
  const formData = row.formData && typeof row.formData === "object" ? row.formData : {};
  return {
    ...formData,
    applicationReference: row.applicationReference ?? formData.applicationReference,
    fullName: row.fullName ?? formData.fullName,
    email: row.email ?? formData.email,
    phone: row.phone ?? formData.phone,
    locale: row.locale ?? formData.locale,
    submittedAt: formData.submittedAt ?? row.createdAt,
    createdAt: row.createdAt,
  };
}
